# Generated by Django 4.0.1 on 2022-05-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0002_rename_image_image_image1_image_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='Name',
        ),
    ]
