# Generated by Django 4.0.1 on 2022-06-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0003_rename_title_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Name',
            new_name='Data',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image2',
        ),
        migrations.AddField(
            model_name='image',
            name='Password',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
