# Generated by Django 4.0.1 on 2022-06-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0004_rename_name_image_data_remove_image_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password2', models.CharField(max_length=20)),
                ('image2', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
