# Generated by Django 4.0.1 on 2022-06-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0005_extract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extract',
        ),
    ]
