# Generated by Django 4.0.1 on 2022-06-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ext_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=20)),
                ('image2', models.ImageField(blank=True, upload_to='extimages')),
            ],
        ),
    ]
